# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 0 * * 1" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: k8scat
          template: classic
          base: header, metadata
          config_timezone: Asia/Shanghai
          # WakaTime plugin: This plugin displays statistics from your WakaTime account.
          plugin_wakatime: false
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: .user.login
          # People plugin: This plugin can display relationships with users, such as followers, sponsors, contributors, stargazers, watchers, members, etc.
          plugin_people: false
          plugin_people_limit: 0
          plugin_people_size: 28
          plugin_people_types: followers
          # Gists: This plugin displays gists stats.
          plugin_gists: false
          
