# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: k8scat
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          # Most used languages
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 180
          plugin_languages_recent.load: 600
          plugin_languages_sections: most-used,recently-used
          plugin_languages_threshold: 0%
          plugin_languages_skipped: goworker
          # Notable contributions
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit,pull_request
          # People plugin: This plugin can display relationships with users, such as followers, sponsors, contributors, stargazers, watchers, members, etc.
          plugin_people: yes
          plugin_people_limit: 0
          plugin_people_size: 28
          plugin_people_types: followers
          # Gists: This plugin displays gists stats.
          plugin_gists: yes
          # WakaTime plugin: This plugin displays statistics from your WakaTime account.
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: .user.login
